### ISSUE TITLE
Dragon-32's Sugestions

### ISSUE THREAD

**Issue by EmperorArthur** [mlox/mlox#2]
Here's a compilation of recent suggestions by @Dragon-32 

If these can be implemented, and a pull request sent, we can see how the whole pull review system is supposed to work.

Some mods have `[NearEnd]` instead of `[NearStart]`.
* German Text Patch [Vrakyas]

Some mods were recently added to the end of the file, instead of where they belong.
* German Text Patch [Vrakyas

Some mods were added, but we can't find them in the wild.
* Magic Diversity 1.1.ESP
* Morrowind Creatures Flying tweaks by Amenophis

To be consistent between all landscape/grass mods a new warning should be added everywhere, or removed completetly.
* Ozzys Grass West Gash and BLSP conflict, but playable

The rules for some mods are incorrect, and should be fixed.
* `Rats Galore by The Wanderer`

There are some extranious order rules.
* `AshVampiresReplacer.ESP` and `Neo's Unique Creatures.esp`

The `<var>` expression can be used with some mods.
* `Magic Diversity.ESP`, `Magic Diversity 1.1.ESP` and `Magic Diversity NO  SOUND.ESP` can be changed to `Magic Diversity <VER>.ESP`
* `Vivec Expansion 2.0.esp` and `Vivec Expansion.DV.esp` ???

`abot` should be on the copyright statement, since he added the update code.

**Comment by Dragon-32** [comment]
I did some fixing up of stuff locally on some of these. I was working on a local clone of mlox/mlox rather than my fork (Dragon-32/mlox). So I think I need to get things back in synch.

As well as the below I've fixed a few other things (e.g. rules Translator 5 pushed caused a Cycle error, caused by a pre-existing Order rule (I think I've found the one) I'd added a while ago. Despite my own "Don't create monolithic Order rules" house rule. Those are a real bitch to track down) and adding a few new plugins.

1
Some mods have `[NearEnd]` instead of `[NearStart]`.  

- German Text Patch [Vrakyas]

2
Some mods were recently added to the end of the file, instead of where they belong.   

- German Text Patch [Vrakyas]

3
To be consistent between all landscape/grass mods a new warning should be added everywhere, or removed completetly.

-  Ozzys Grass West Gash and BLSP conflict, but playable

4
The rules for some mods are incorrect, and should be fixed.

- Rats Galore by The Wanderer

5
There are some extranious order rules.

- AshVampiresReplacer.ESP and Neo's Unique Creatures.esp

**Comment by Dragon-32** [comment]
Got changes (where needed) for all of these locally, should find their way into the next release of the rule-set

**Comment by EmperorArthur** [comment]
With Pull #12 merged, can this be closed?

**Comment by Dragon-32** [comment]
I'd always closed Issues like this when a new mlox_base had been released but I guess so, yeah.

Been away for a fortnight, just catching up with stuff.

**Comment by EmperorArthur** [comment]
Latest mlox_base has been released!!!

Closing this issue.
